version: "3.9"
services:
  web:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "4000:4000"
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
